# TASK level variables
- name: variables from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"
    Trainer: "Prema"
    Duration: "110HRS"
  tasks: 
   - name: check variables
     vars: #task level
      Course: "DevOps with AWS"
      Trainer: "Kishore"
      Duration: "250HRS"
     ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
