- name: variables from PLACE level
  hosts: localhost
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: PERSON
    prompt: please enter your name
    private: false # user can see what they are entering
  - name: PLACE
    prompt: please enter your place
    private: false # user can see what they are entering
  vars:
    PERSON: "Prema from SKHT"             # play
    TRAVELLING: "SKHT to BNGLR" 
  tasks: 
   - name: check variables
     vars: 
      PERSON: "Prema from PUNE"             #task
      TRAVELLING: "HYD to PUNE" 
     ansible.builtin.debug:
      msg: "Hello {{PERSON}}, Good {{TRAVELLING}}"



   #1.CMD
   #2.place
   #3.file
   #4.prompt   